disable eslint if the logic needs to be != null
Got warning in SPFx 1.15.2 new web part
```console
[00:55:35] Warning - lint - src\webparts\listAPalooza\pnpjsConfig.ts(15,15): error eqeqeq: Expected '!==' and instead saw '!='.
```